### ISSUE TITLE
Where did these four documents come from?

### ISSUE THREAD

**Issue by reBiocoder** [shirley-wu/text_to_table#1]
train.text  train.data valid.text valid.data test.text test.data

**Comment by shirley-wu** [comment]
Hi, sorry for the late response. You should download the data from [Google Drive](https://drive.google.com/file/d/1zTfDFCl1nf_giX7IniY5WbXi9tAuEHDn/view). The zip file contains 4 directories (each for one dataset), and each directory contains 6 files {train,valid,test}.{text,data}

**Comment by reBiocoder** [comment]
@shirley-wu  thanks! Great job：）
