### ISSUE TITLE
How to find the files 'dict.data.txt' and 'dict.text.txt'

### ISSUE THREAD

**Issue by Gnightood** [shirley-wu/text_to_table#10]
Hello, I don't know where to find the files 'dict.data.txt' and 'dict.text.txt'. I couldn't find them in data/rotowire/bins.

**Comment by shirley-wu** [comment]
Hi, I don't think you need these two files? I think you only need ${BART_DIR}/dict.txt

**Comment by Jason-will3** [comment]
By the way, where is dict.txt actually from? I also cant find it in the file path

**Comment by Jason-will3** [comment]
I try to run the code on colab and using command :
"! bash /content/drive/MyDrive/PaperCode/text_to_table/scripts/preprocess.sh  /content/drive/MyDrive/data/rotowire/ bart.base/"

And get error:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/PaperCode/text_to_table/bart.base/dict.txt'
