### ISSUE TITLE
Dataset conversion scripts

### ISSUE THREAD

**Issue by pietrolesci** [shirley-wu/text_to_table#3]
Hi @shirley-wu,

I hope you are doing well. 

I am looking at the codebase to find the script that translates the table2text data into the text2table format (eg, rotowire). However, I did not manage to find it. Is it available somewhere?

Thank you very much in advance for your time!

Best,
Pietro

**Comment by shirley-wu** [comment]
Hi, sorry that I do not fully understand your question. Do you mean the scripts to convert **original** table2text dataset into our released text2table data?

**Comment by pietrolesci** [comment]
Hi @shirley-wu, thanks for your answer. Exactly!

**Comment by shirley-wu** [comment]
Thanks for your reply! The scripts aren't available for now but I'll be happy to release them if you need. I'll need some time to clean up the scripts (I'll guess I can finish by 10/15). I'll update this issue again after it's finished.

**Comment by shirley-wu** [comment]
Hi I just pushed the scripts to [data_preprocessing](https://github.com/shirley-wu/text_to_table/tree/main/data_preprocessing)

**Comment by pietrolesci** [comment]
Hi @shirley-wu, thank you very much for acting so quickly on this! 🚀
