### ISSUE TITLE
The BERT scores are mismatching while training, so  did you use any other script for evaluation.

### ISSUE THREAD

**Issue by Roshan818** [shirley-wu/text_to_table#4]

**Comment by shirley-wu** [comment]
Hi, what do you mean by the BERT scores are mismatching while training?

We do not need to calculate BERT scores during training. As in the README, `bert_score` package is not used by the training script. We have separate scripts for evaluation, i.e., `scripts/dataset-name/test_vanilla.sh` and `scripts/dataset-name/test_constraint.sh`. Please refer to our [README](https://github.com/shirley-wu/text_to_table/blob/main/README.md#inference-and-evaluation) for details.

**Comment by haorui-harry** [comment]
我只想把text 转成table，我的数据只提供text，应该怎么做，我希望得到我的text对应的table

**Comment by shirley-wu** [comment]
@harryniuby 你可以尝试用我发布的数据训练一个模型，然后用你的文本infer。但是我不确定效果怎么样
