### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by KevinXu11155** [shirley-wu/text_to_table#9]
When I was running '!bash scripts/rotowire/test_constraint.sh data/rotowire/ '.
There is always 'OSError: Model file not found: checkpoints/checkpoint_average_best-3.pt'
and Row header: precision = nan; recall = nan; f1 = nan
Col header: precision = nan; recall = nan; f1 = nan
Non-header cell: precision = nan; recall = nan; f1 = nan
What happened? How to fix this.
Thank you for you reply

**Comment by shirley-wu** [comment]
Hi this means the training fails, so there's no checkpoint of trained model. But I need to see more logs to know what happened. Are there more error log? And can you check the content in checkpoints/log to see if there're more logs?

**Comment by KevinXu11155** [comment]
I have retrained the model and the issue has been resolved(I don't know why. All the steps are the same).

**Comment by KevinXu11155** [comment]
Thank you for your help

**Comment by shirley-wu** [comment]
Glad to know that! Feel free to reopen this issue if you figure out what's wrong with this repo
